CREATE DATABASE HotelManagement
GO

USE HotelManagement
GO

CREATE TABLE KhachHang (
	MaKH VARCHAR(20) NOT NULL,
	CCCD VARCHAR(50) NOT NULL,
	SDT_KH VARCHAR(15) NOT NULL,
	HoTen NVARCHAR(100) NOT NULL,
	GioiTinh NVARCHAR(10) NOT NULL,
	DiaChi NVARCHAR(100),
	QuocTich NVARCHAR(50),
	Email_KH VARCHAR(100),
	CONSTRAINT PK_KhachHang PRIMARY KEY (MaKH)
)
GO

CREATE TABLE NhanVien (
	MaNV VARCHAR(20) NOT NULL,
	CCCD VARCHAR(50) NOT NULL,
	HoTen NVARCHAR(100) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh NVARCHAR(10) NOT NULL,
	ChucVu NVARCHAR(50) NOT NULL,
	SDT_NV VARCHAR(15) NOT NULL,
	Email_NV VARCHAR(100) NOT NULL,
	DiaChi NVARCHAR(100) NOT NULL,
	SoBHYT VARCHAR(50) NOT NULL,
	SoHopDong VARCHAR(50) NOT NULL,
	NamBatDau INT NOT NULL,
	MaSoThueCaNhan VARCHAR(50) NOT NULL,
	CONSTRAINT PK_NV PRIMARY KEY (MaNV)
)
GO

CREATE TABLE LichLam (
	NgayLam DATE NOT NULL,
	MaNV VARCHAR(20) NOT NULL,
	CaLam NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_LichLam PRIMARY KEY(MaNV, NgayLam),
	CONSTRAINT FK_LichLam_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
)
GO

CREATE TABLE Luong (
	MaNV VARCHAR(20) NOT NULL,
	MucLuong DECIMAL(10,0) NOT NULL,
	Thuong DECIMAL(10, 2),
	Phat DECIMAL(10, 2),
	PhuCap DECIMAL(10, 2),
	ThangLuong DATE NOT NULL,
	CONSTRAINT PK_Luong PRIMARY KEY (MaNV, ThangLuong),
	CONSTRAINT FK_Luong_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE ON UPDATE CASCADE
)
GO

CREATE TABLE LoaiPhong (
	MaLP VARCHAR(20) NOT NULL,
	TenLP NVARCHAR(50) NOT NULL,
	SucChua INT NOT NULL,
	SoGiuong INT NOT NULL,
	DienTich DECIMAL(5, 2) NOT NULL,
	TienNghi NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_LoaiPhong PRIMARY KEY (MaLP)
)
GO

CREATE TABLE Phong (
	MaP VARCHAR(20) NOT NULL,
	MaLP VARCHAR(20) NOT NULL,
	TrangThai NVARCHAR(50) NOT NULL,
	GiaMacDinh DECIMAL(10, 2) NOT NULL,
	CONSTRAINT PK_Phong PRIMARY KEY (MaP),
	CONSTRAINT FK_Phong FOREIGN KEY (MaLP) REFERENCES LoaiPhong(MaLP) ON DELETE CASCADE
)
GO

CREATE TABLE HoaDonPhong (
	MaHDP VARCHAR(20) NOT NULL,
	MaNV VARCHAR(20) NOT NULL,
	MaKH VARCHAR(20) NOT NULL,
	NgayDat DATE NOT NULL,
	CONSTRAINT PK_HoaDonPhong PRIMARY KEY (MaHDP),
	CONSTRAINT FK_HoaDonPhong_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE,
	CONSTRAINT FK_HoaDonPhong_NV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
)
GO

CREATE TABLE CTHDPhong (
	MaCTHDP VARCHAR(20) NOT NULL,
	MaHDP VARCHAR(20) NOT NULL,
	MaP VARCHAR(20) NOT NULL,
	NgayNhan DATE NOT NULL,
	NgayTra DATE NOT NULL,
	TrangThai NVARCHAR(50) NOT NULL DEFAULT N'Chưa thanh toán',
	CONSTRAINT PK_CTHDPhong PRIMARY KEY (MaCTHDP),
	CONSTRAINT FK_CTHDPhong_HoaDonPhong FOREIGN KEY (MaHDP) REFERENCES HoaDonPhong(MaHDP) ON DELETE CASCADE,
	CONSTRAINT FK_CTHDPhong_Phong FOREIGN KEY (MaP) REFERENCES Phong(MaP) ON DELETE CASCADE ON UPDATE CASCADE
)
GO

CREATE TABLE Mon (
	MaMon VARCHAR(20) NOT NULL,
	TenMon NVARCHAR(100) NOT NULL,
	GiaMon DECIMAL(10, 2) NOT NULL,
	TrangThai_Mon VARCHAR(20) NOT NULL DEFAULT ('available'),
	CONSTRAINT PK_Mon PRIMARY KEY (MaMon)
)
GO

CREATE TABLE HoaDonMon (
	MaHDM VARCHAR(20) NOT NULL,
	MaNV VARCHAR(20) NOT NULL,
	MaKH VARCHAR(20) NOT NULL,
	NgayDat DATE NOT NULL,
	CONSTRAINT PK_HoaDonMon PRIMARY KEY (MaHDM),
	CONSTRAINT FK_HoaDonMon_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE,
	CONSTRAINT FK_HoaDonMon_NV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
)
GO

CREATE TABLE CTHDMon (
	MaCTHDM VARCHAR(20) NOT NULL,
	MaHDM VARCHAR(20) NOT NULL,
	MaP VARCHAR(20) NOT NULL,
	MaMon VARCHAR(20) NOT NULL,
	SL_Mon INT NOT NULL,
	NgaySD DATE NOT NULL,
	TrangThai NVARCHAR(50) NOT NULL DEFAULT N'Chưa thanh toán',
	CONSTRAINT PK_CTHDMon PRIMARY KEY (MaCTHDM),
	CONSTRAINT FK_CTHDMon_HoaDonMon FOREIGN KEY (MaHDM) REFERENCES HoaDonMon(MaHDM) ON DELETE CASCADE,
	CONSTRAINT FK_CTHDMon_Phong FOREIGN KEY (MaP) REFERENCES Phong(MaP) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_CTHDMon_Mon FOREIGN KEY (MaMon) REFERENCES Mon(MaMon) ON DELETE CASCADE ON UPDATE CASCADE
)
GO

CREATE TABLE DichVu (
	MaDV VARCHAR(20) NOT NULL,
	TenDV NVARCHAR(100) NOT NULL,
	GiaDV DECIMAL(10, 2) NOT NULL,
	Loai_DV NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_DichVu PRIMARY KEY (MaDV)
)
GO

CREATE TABLE HoaDonDV (
	MaHDDV VARCHAR(20) NOT NULL,
	MaKH VARCHAR(20) NOT NULL,
	MaNV VARCHAR(20) NOT NULL,
	NgayDat DATE NOT NULL,
	CONSTRAINT PK_HDDV PRIMARY KEY (MaHDDV),
	CONSTRAINT FK_HoaDonDV_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE,
	CONSTRAINT FK_HoaDonDV_NV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
)
GO

CREATE TABLE CTHDDichVu (
	MaCTHDDV VARCHAR(20) NOT NULL,
	MaHDDV VARCHAR(20) NOT NULL,
	MaDV VARCHAR(20) NOT NULL,
	SL_DV INT NOT NULL,
	MaP VARCHAR(20) NOT NULL,
	NgaySD DATE NOT NULL,
	TrangThai VARCHAR(50) NOT NULL DEFAULT N'Chưa thanh toán',
	CONSTRAINT PK_CTHDDV PRIMARY KEY (MaCTHDDV),
	CONSTRAINT FK_CTHDDV_HoaDonDV FOREIGN KEY (MaHDDV) REFERENCES HoaDonDV(MaHDDV) ON DELETE CASCADE,
	CONSTRAINT FK_CTHDDV_Phong FOREIGN KEY (MaP) REFERENCES Phong(MaP) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_CTHDDV_DichVu FOREIGN KEY (MaDV) REFERENCES DichVu(MaDV) ON DELETE CASCADE ON UPDATE CASCADE
)
GO

CREATE TABLE HoaDon (
	MaHD VARCHAR(20) NOT NULL,
	MaKH VARCHAR(20) NOT NULL,
	MaNV VARCHAR(20) NOT NULL,
	MaLoaiHD VARCHAR(20) NOT NULL,
	NgayXuatHD DATE,
	TrangThai NVARCHAR(50) NOT NULL DEFAULT N'Chưa thanh toán',
	CONSTRAINT PK_HoaDon PRIMARY KEY (MaHD, MaLoaiHD),
	CONSTRAINT FK_HoaDon_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE,
	CONSTRAINT FK_HoaDon_NV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
)
GO

CREATE TABLE CTHD (
	MaCTHD VARCHAR(20) NOT NULL,
	MaHD VARCHAR(20) NOT NULL,
	MaLoaiHD VARCHAR(20) NOT NULL,
	MaKH VARCHAR(20) NOT NULL,
	MaLoaiCTHD VARCHAR(20) NOT NULL,
	CONSTRAINT PK_CTHD PRIMARY KEY (MaCTHD, MaLoaiHD),
	CONSTRAINT FK_CTHD_HoaDon FOREIGN KEY (MaHD, MaLoaiHD) REFERENCES HoaDon(MaHD, MaLoaiHD),
	CONSTRAINT FK_CTHD_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE
)